### ISSUE TITLE
Bug in slot-set!

### ISSUE THREAD

**Issue by ChrisVine** [fedeinthemix/chez-matchable#1]
Thanks for the port of the Shinn matcher to chez scheme.  It works well except that there is a bug in the implementation of the slot-set! macro.

The following code should show the mutation of the best-friend field, but in fact it fails to compile:
`(define-record-type person (fields name (mutable best-friend)))
(define p (make-person "Mary" "Don"))
(display p)(newline)
(match p
  [($ person :_ (set! b))
   (b "Donna")])
(display p)(newline)`

The problem is that the slot-set! macro needs to take a fourth argument (the value to be set) which should be passed as a second argument to the procedure returned by the application of record-mutator.

So this works:
`  (define-syntax slot-set!
    (syntax-rules ()
      ((_ rtn rec n val)
       (let ((n: n)
             (rec: rec))
         (if (number? n:)
             ((record-mutator (record-rtd rec:) n:) rec: val)
             ;; If it's not a number, then it should be a symbol with
             ;; the name of a field.
             (let* ((rtd (record-rtd rec:))
                    (fields (record-type-field-names rtd))
                    (fields-idxs (map (lambda (f i) (cons f i))
                                      (vector->list fields)
                                      (iota (vector-length fields))))
                    (idx (cdr (assv n: fields-idxs))))
               ((record-mutator rtd idx) rec: val)))))))`

Note also that I have avoided multiple evaluations of n and rec (I don't know whether that is in fact a problem), which is a point which also affects the other two macros.

**Comment by ChrisVine** [comment]
Well the display of the code has elided all the lines of the code.  How weird.  Anyway I think you can follow the point and reinsert the formatting.

**Comment by fedeinthemix** [comment]
Fixed thanks!
